DROP DATABASE IF EXISTS `UserDB`;
CREATE DATABASE IF NOT EXISTS `UserDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `UserDB`;

DROP TABLE IF EXISTS `gender`;
CREATE TABLE IF NOT EXISTS `userDetails`